const CHANGE_PROGRESS = "app/courses/CHANGE_PROGRESS";
const CHANGE_PROGRESS_SUCCESS = "app/courses/CHANGE_PROGRESS_SUCCESS";
const CHANGE_ACTIVE_LESSON = "app/courses/CHANGE_ACTIVE_LESSON";
const CHANGE_ACTIVE_LESSON_SUCCESS = "app/courses/CHANGE_ACTIVE_LESSON_SUCCESS";
const INIT_COURSE = "app/courses/INIT_COURSE";
const INIT_COURSE_SUCCESS = "app/courses/INIT_COURSE_SUCCESS";
const API_ERROR = "app/courses/API_ERROR";

const types = {
  CHANGE_PROGRESS,
  CHANGE_PROGRESS_SUCCESS,
  CHANGE_ACTIVE_LESSON,
  CHANGE_ACTIVE_LESSON_SUCCESS,
  INIT_COURSE,
  INIT_COURSE_SUCCESS,
  API_ERROR,
};

export default types;
